### ISSUE TITLE
docker-compose.yml

### ISSUE THREAD

**Issue by danielbadry** [kibatic/docker-proftpd#1]
hi
please help me to create and config docker-compose.yml .
tnx
@philippe-levan @eliecharra

**Comment by philippe-levan** [comment]
hi @danielbadry ,

I added a docker-compose.yml example in the readme.

fixed by commit : https://github.com/kibatic/docker-proftpd/commit/1fc0ada826df7f7bd569ede0f116ac086ed1e1b9

Best regards,
Philippe

**Comment by danielbadry** [comment]
It Worked for Me .
tanx
@philippe-levan
